stages:
  - mirror
  - test
  - release
  - deploy

github_mirror:
  stage: mirror
  tags:
    - github_namboy94_push
  script:
    - git checkout master
    - git pull
    - git push git@github.com:namboy94/champlates.git master -f
    - git checkout develop
    - git pull
    - git push git@github.com:namboy94/champlates.git develop -f

lint:
  stage: test
  tags:
    - php
    - composer
  script:
    - composer update
    - ./lint.sh

unittest:
  stage: test
  tags:
    - composer
    - php
    - coverage
  script:
    - echo $TEST_DB_PASS > DB_PASS.secret
    - composer update
    - ./unittest.sh
    - rsync -av coverage/ /var/www/coverage.namibsun.net/public_html/champlates --delete-before
    - rm DB_PASS.secret

upload_release_to_github:
  stage: release
  only:
    - master
  tags:
    - python
    - linux
  script:
    - mkdir -p artifacts
    - git clone https://gitlab.namibsun.net/namboy94/ci-scripts.git
    - python ci-scripts/src/changelog-reader/changelog-reader.py -c CHANGELOG -d current_changelog
    - python ci-scripts/src/github-release-uploader/github-release-uploader.py namboy94 champlates $GITHUB_ACCESS_TOKEN
      $(cat version) current_changelog artifacts -b master

upload_release_to_gitlab:
  stage: release
  only:
    - master
  tags:
    - python
    - linux
  script:
    - mkdir -p artifacts
    - git clone https://gitlab.namibsun.net/namboy94/ci-scripts.git
    - python ci-scripts/src/changelog-reader/changelog-reader.py -c CHANGELOG -d  current_changelog
    - python ci-scripts/src/gitlab-release-uploader/gitlab-release-uploader.py namboy94 champlates $GITLAB_ACCESS_TOKEN
      $(cat version) current_changelog artifacts -b master -u https://gitlab.namibsun.net

deploy_develop_webpage:
  stage: deploy
  only:
    - master
    - develop
  tags:
    - champlates-develop
  script:
    - ./deploy.sh

deploy_live_webpage:
  stage: deploy
  only:
    - master
  tags:
    - champlates-live
  script:
    - export LIVE=1
    - ./deploy.sh
